source "https://api.berkshelf.com"

cookbook "apache2", '~> 3.0.0'
cookbook "application"
cookbook "application_ruby"
cookbook "apt", :github => "opscode-cookbooks/apt"
cookbook "auditd"
cookbook "awstats"
cookbook "backup", :github => "danfruehauf/backup-cookbook"
cookbook "build-essential"
cookbook "chef-solo-search", :github => "edelight/chef-solo-search"
cookbook "chef_handler"
cookbook "cron"
cookbook "database"
cookbook "database_migrations", :path => "cookbooks/database_migrations"
cookbook "git", :github => "opscode-cookbooks/git"
cookbook "git_ssh_wrapper", :github => "foldr/chef-git_ssh_wrapper"
cookbook "grails", :path => "cookbooks/grails"
cookbook "hostname", :github => "3ofcoins/chef-cookbook-hostname"
cookbook "htpasswd", :github => "Youscribe/htpasswd-cookbook"
cookbook "imos_apache2", :path => "cookbooks/imos_apache2"
cookbook "imos_artifacts", :path => "cookbooks/imos_artifacts"
cookbook "imos_backup", :path => "cookbooks/imos_backup"
cookbook "imos_core", :path => "cookbooks/imos_core"
cookbook "imos_depth_service", :path => "cookbooks/imos_depth_service"
cookbook "imos_devel", :path => "cookbooks/imos_devel"
cookbook "imos_dns", :path => "cookbooks/imos_dns"
cookbook "imos_firewall", :path => "cookbooks/imos_firewall"
cookbook "imos_java", :path => "cookbooks/imos_java"
cookbook "imos_jenkins", :path => "cookbooks/imos_jenkins"
cookbook "imos_logstash", :path => "cookbooks/imos_logstash"
cookbook "imos_mounts", :path => "cookbooks/imos_mounts"
cookbook "imos_po", :path => "cookbooks/imos_po"
cookbook "imos_postgresql", :path => "cookbooks/imos_postgresql"
# If you're going to use ':github =>', instead of ':git =>', the ':rel argument
# will not work!!
cookbook "imos_python", :git => "https://github.com/aodn/cookbooks.git", :rel => "imos_python"
cookbook "imos_squid", :path => "cookbooks/imos_squid"
cookbook "imos_task_spooler", :path => "cookbooks/imos_task_spooler"
cookbook "imos_users", :path => "cookbooks/imos_users"
cookbook "imos_vsftpd", :path => "cookbooks/imos_vsftpd"
cookbook "imos_webapps", :path => "cookbooks/imos_webapps"
cookbook "java", :github => "socrata-cookbooks/java"
cookbook "jenkins", :github => "opscode-cookbooks/jenkins"
cookbook "kibana", :github => "lusis/chef-kibana"
cookbook "logrotate"
cookbook "logstash", :github => "lusis/chef-logstash"
cookbook "minitest-handler",:github => "btm/minitest-handler-cookbook"
cookbook "mysql", :path => "cookbooks/mysql"
cookbook "nagios", :path => "cookbooks/nagios"
cookbook "nginx", :github => "opscode-cookbooks/nginx"
cookbook "nfs", :github => "atomic-penguin/cookbook-nfs"
cookbook "ntp"
cookbook "ohai", :github => "opscode-cookbooks/ohai", :ref => "v1.1.12"
cookbook "ohai_plugins", :path => "cookbooks/ohai_plugins"
cookbook "omnibus_updater"
cookbook "packer", :github => "sit/chef-packer"
cookbook "postfix"
cookbook "python"
cookbook "ramadda", :path => "cookbooks/ramadda"
cookbook "rbenv", :github => "fnichol/chef-rbenv"
cookbook "route53", :github => "hw-cookbooks/route53"
cookbook "rsync"
cookbook "rsync_chroot", :github => "danfruehauf/rsync_chroot"
cookbook "imos_rsync", :path => "cookbooks/imos_rsync"
cookbook "samba", :github => "aodn/samba-cookbook"
cookbook "sofs", :path => "cookbooks/sofs"
cookbook "squid", :github => "opscode-cookbooks/squid", :ref => "v0.5.0"
cookbook "subversion", :github => "opscode-cookbooks/subversion", :ref => "v1.0.4"
cookbook "sudo"
cookbook "ssl", :github => "cap10morgan/ssl-cookbook"
cookbook "sysctl", :github => "Youscribe/sysctl-cookbook"
cookbook "talend", :path => "cookbooks/talend"
cookbook "external_templates", :path => "private/external_templates"
cookbook "timezone-ii", :github => "L2G/timezone-ii"
cookbook "tomcat", :path => "cookbooks/tomcat"
cookbook "unattended_upgrades"
cookbook "users"
cookbook "vsftpd"
cookbook "windows"
cookbook "xvfb"
