source 'https://supermarket.chef.io'

cookbook 'application', '= 4.1.6' # pinned for Chef 12.3.0 compatibility
cookbook 'application_ruby'
cookbook 'apt'
cookbook 'auditd'
cookbook 'awstats'
cookbook 'build-essential'
cookbook 'chef-solo-search'
cookbook 'chef_handler'
cookbook 'cron'
cookbook 'git'
cookbook 'hostname'
cookbook 'htpasswd'
cookbook 'java'
cookbook 'jenkins'
cookbook 'logrotate'
cookbook 'minitest-handler'
cookbook 'mysql', '= 6.1.2' # pinned for Chef 12.3.0 compatibility
cookbook 'ntp'
cookbook 'omnibus_updater'
cookbook 'postfix'
cookbook 'poise-python'
cookbook 'ruby_rbenv'
cookbook 'route53'
cookbook 'rsync'
cookbook 'rabbitmq'
cookbook 'smf'
cookbook 'sudo'
cookbook 'supervisor'
cookbook 'ssl'
cookbook 'sysctl'
cookbook 'timezone_lwrp'
cookbook 'unattended_upgrades'
cookbook 'users'
cookbook 'vsftpd'
cookbook 'windows'
cookbook 'xvfb'

cookbook 'apache2', :path=> 'cookbooks/apache2-cookbook' # Forked GitHub version required due to mod_php 7 support being "in progress" upstream
cookbook 'backup', :path => 'cookbooks/backup-cookbook'
cookbook 'git_ssh_wrapper', :path => 'cookbooks/chef-git_ssh_wrapper'
cookbook 'imos_apache2', :path => 'cookbooks/imos_apache2'
cookbook 'imos_artifacts', :path => 'cookbooks/imos_artifacts'
cookbook 'imos_backup', :path => 'cookbooks/imos_backup'
cookbook 'imos_chef_solo', :path => 'cookbooks/imos_chef_solo'
cookbook 'imos_core', :path => 'cookbooks/imos_core'
cookbook 'imos_postfix', :path => 'cookbooks/imos_postfix'
cookbook 'imos_devel', :path => 'cookbooks/imos_devel'
cookbook 'imos_dns', :path => 'cookbooks/imos_dns'
cookbook 'imos_firewall', :path => 'cookbooks/imos_firewall'
cookbook 'imos_java', :path => 'cookbooks/imos_java'
cookbook 'imos_jenkins', :path => 'cookbooks/imos_jenkins'
cookbook 'imos_mounts', :path => 'cookbooks/imos_mounts'
cookbook 'imos_po', :path => 'cookbooks/imos_po'
cookbook 'imos_postgresql', :path => 'cookbooks/imos_postgresql'
cookbook 'imos_squid', :path => 'cookbooks/imos_squid'
cookbook 'imos_task_spooler', :path => 'cookbooks/imos_task_spooler'
cookbook 'imos_users', :path => 'cookbooks/imos_users'
cookbook 'imos_vsftpd', :path => 'cookbooks/imos_vsftpd'
cookbook 'imos_webapps', :path => 'cookbooks/imos_webapps'
cookbook 'imos_websites', :path => 'cookbooks/imos_websites'
cookbook 'nagios', :path => 'cookbooks/nagios'
cookbook 'packer', :path => 'cookbooks/chef-packer'
cookbook 'rsync_chroot', :path => 'cookbooks/rsync_chroot'
cookbook 'imos_rsync', :path => 'cookbooks/imos_rsync'
cookbook 's3fs-fuse', :path => 'cookbooks/s3fs-fuse'
cookbook 'talend', :path => 'cookbooks/talend'
cookbook 'external_templates', :path => 'private/external_templates'
cookbook 'squid', :path => 'forked_cookbooks/squid'
cookbook 'tomcat', :path => 'cookbooks/tomcat'
