default["imos_jenkins"]["plugins"] = %w{
  aws-java-sdk
  build-name-setter
  build-pipeline-plugin
  copyartifact
  envinject
  git
  git-client
  grails
  greenballs
  job-log-logger-plugin
  maven-plugin
  postbuildscript
  repository
  role-strategy
  s3
  throttle-concurrents
  token-macro
  validating-string-parameter
  xvfb
}
