#!/bin/bash

# Written by Dan Fruehauf <dan.fruehauf@utas.edu.au>

#
# This script checks for the number of URLs served by NcWMS server. Usually
# NcWMS server will provide us with many <href>s of type GetMap or
# GetFeatureInfo. We will count them and alert if they are too low.
# Example usage:
# check_ncwms -c 800 -w 1000 -t GetMap -u https://ncwms.aodn.org.au/
# This will alert if there are less than 1000 GetMap URLs as warning and as
# critical if there are less than 800.
#

# how does the url looks like? usually something like:
# 'a href="wms?REQUEST=GetMap&...'
# 'a href="wms?REQUEST=GetFeatureInfo&...'
declare WMS_REQUEST_PREFIX="<a href=\"wms?REQUEST="

# checks ncwms layers
# $1 - ip address
# $2 - ncwms URL
# $3 - request type (GetMap, GetFeatureInfo)
# $4 - warning
# $5 - critical
check_ncwms() {
    local ip_address=$1; shift
    local url="$1"; shift
    local request_type="$1"; shift
    local -i warning=$1; shift
    local -i critical=$1; shift

    tmp_output=`mktemp`
    local host=`echo $url | cut -d/ -f3`
    local resolve_args="--resolve $host:80:$ip_address --resolve $host:443:$ip_address"
    curl $resolve_args -o $tmp_output -L -s $url
    if [ $? -ne 0 ]; then
        ERROR_STRING="curl error"
        rm -f $tmp_output
        return 2 # 2 for CRITICAL
    fi

    # see how many time this request is there
    local -i request_nr=`grep -c "${WMS_REQUEST_PREFIX}${request_type}" $tmp_output`
    rm -f $tmp_output

    # format string for user
    local error_string="${request_type}: serving $request_nr URLs"

    if [ $request_nr -lt $critical ]; then
        echo "Critical: $error_string"
        return 2
    elif [ $request_nr -lt $warning ]; then
        echo "Warning: $error_string"
        return 1
    else
        echo "OK: $error_string"
        return 0
    fi
}

# prints usage and exit
usage() {
    echo "Usage: $0 [OPTIONS]... NODE_NAME"
    echo "Checks number of URLs served by NcWMS server."
    echo "
Options:
  -I, --ip-address           NcWMS IP address.
  -u, --url                  NcWMS URL.
  -t, --type                 Request type (GetMap, GetFeatureInfo).
  -w, --warning              Warning threshold.
  -c, --critical             Critical threshold."
    exit 3
}


# "$@" - parameters, see usage
main() {
    # parse options with getopt
    local tmp_getops=`getopt -o hI:u:t:w:c: --long help,ip-address:,url:,type:,warning:,critical: -- "$@"`
    [ $? != 0 ] && usage

    eval set -- "$tmp_getops"
    local url type
    local -i warning=0
    local -i critical=0

    # parse the options
    while true ; do
        case "$1" in
            -h|--help) usage;;
            -I|--ip-address) ip_address="$2"; shift 2;;
            -u|--url) url="$2"; shift 2;;
            -t|--type) type="$2"; shift 2;;
            -w|--warning) warning="$2"; shift 2;;
            -c|--critical) critical="$2"; shift 2;;
            --) shift; break;;
            *) usage;;
        esac
    done

    [ x"$ip_address" = x ] && usage
    [ x"$url" = x ] && usage
    [ x"$type" = x ] && usage

    check_ncwms $ip_address "$url" "$type" $warning $critical
}

main "$@"
