driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
    run_list: apt::default
  - name: debian-8.6
    run_list: apt::default
  - name: fedora-25
  - name: freebsd-10.3
  - name: opensuse-leap-42.1
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
  - name: default
    run_list:
      - recipe[squid::default]
    excludes:
      - fedora-25
      - centos-7.3
      - centos-6.8
    attributes:
      squid:
        cache_size: 10
        cache_mem: 10
  - name: selinux
    run_list:
      - recipe[squid::selinux]
      - recipe[squid::default]
    includes:
      - fedora-25
      - centos-7.3
      - centos-6.8
    attributes:
      squid:
        cache_size: 10
        cache_mem: 10
