#!/bin/bash

# transform a bucket uri (s3://something/dir/file) to a file path under /mnt
# like /mnt/something/dir/file
bucket_uri_to_file_path() {
    local bucket_uri=$1; shift
    echo $bucket_uri | sed -e 's#s3://#/s3/#'
}

# main
main() {
    local cmd src dst
    while [ x"$1" != x ]; do
        if [ "$1" = "-m" ]; then
            shift
        elif [ "${1:0:1}" = "-" ]; then
            true
        elif [ x"$cmd" = x ]; then
            cmd=$1
        elif [ x"$src" = x ]; then
            src=$1
        elif [ x"$dst" = x ]; then
            dst=$1
        fi
        shift
    done

    [ x"$cmd" = x ] && echo "Command not specified" && exit 1
    [ x"$src" = x ] && echo "Source file not specified" && exit 1

    if [ "$cmd" == "sync" ] || [ "$cmd" == "put" ]; then
        [ x"$dst" = x ] && echo "Destination not specified" && exit 1
        dst=`bucket_uri_to_file_path $dst` && \
            mkdir -p `dirname $dst` && \
            sudo chmod 664 $src && \
            cp $src $dst
    elif [ "$cmd" == "get" ]; then
        [ x"$dst" = x ] && echo "Destination not specified" && exit 1
        src=`bucket_uri_to_file_path $src` && \
            cp $src $dst
    elif [ "$cmd" == "del" ]; then
        src=`bucket_uri_to_file_path $src` && \
            rm -f $src
    elif [ "$cmd" == "ls" ]; then
        src=`bucket_uri_to_file_path $src` && \
        if test -d $src; then
            ls -1 $src | sed -e 's/^/dummy dummy dummy /' # mock 3 fields like s3cmd
        fi
    else
        echo "Unknown command '$cmd'" && exit 1
    fi
}

main "$@"
